// class that generates acronyms by the following algorithm:
// Generate acronym by calling generateAcronym()
// Acronym is generated by randomly selecting a letter from the alphabet
// and adding it to the acronym. If dots are to be added, a dot is added
// letters are selected by the defined distribution

#include <string>
#include <random>
#include <iostream>

#include "AcronymGenerator.h"

#define ALPHABET_SIZE 26

std::string AcronymGenerator::generateAcronym(int length, bool addDots) {
  std::random_device rd;
  std::mt19937 gen(rd());
  std::discrete_distribution<> letterDist(probs, probs + ALPHABET_SIZE);
  std::string acronym = "";
  for (int i = 0; i < length; i++) {
    char letter = letters[letterDist(gen)];
    acronym += letter;
    if (addDots && i < length - 1) {
      acronym += ".";
    }
  }
  return acronym;
}
